server:
  port: 8801

eureka:
  client:
    #    在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
#     因为当前服务就是注册中心 不需要向任何人注册
    #    eureka.client. register-with-eureka:由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    registerWithEureka: false
    #    eureka. client . fetch-registry:由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false。
#      不主动发现别人
    fetchRegistry: false
    #    声明注册中心的地址  注册中心1 向 注册中心2 注册
    serviceUrl:
      defaultZone: http://localhost:8800/eureka/

#给当前应用起个服务名称 不能通过路径访问的  这个服务名称 是微服务中使用代表当前服务
#可以认为是当前应用服务的用户名
spring:
  application:
    name: eureka-server1